### PR TITLE
Proposed fix to keepalive

### PR DESCRIPTION
**Pull request by hiddos**
This _should_ fix the keepalive not working. It's in correspondence with Discord's API.

I haven't been able to test this, I'd like someone else to try it and report whether it works.

### CODE REVIEW

**Comment by hiddos** [comment]
If class variables (integers that is) are always initialized to 0 then that line can be left away. The point of storing it is you have to send the last sequence number you received back to discord in the heartbeat request.

**Comment by hiddos** [comment]
It needs to be tested still yes. Note that I'm using this same code without issue.

I adjusted the commit to integrate your style guide comments

**Comment by Aidoboy** [comment]
Oh, you're right. I'm short on sleep and for some reason thought it was set to 0 in `on_message`. I'll try to get to testing it soon.

**Comment by hiddos** [comment]
I probably fixed it. I tested it through aidobot. It works and I can sustain a connection.

The fix comes in two parts. First you needed to specify the API version you were using in the gateway URI, so that Discord can send you an OP 10 Hello.

Second, in the OP 10 there is the identify call (after which you receive a READY event, but you don't need to do anything there). OP 10 also contains the heartbeat_interval, trying to get it from READY just results in a crash since it's not sent there (it probably was in an older API version).

**Pull request merged**
